### ISSUE TITLE
friend link of caoyudong is wrong

### ISSUE THREAD

**Issue by lao605** [liuqipeng417/liuqipeng417.github.io#1]
i see this: http//caoyudong.com/ , which should be http://caoyudong.com/

please fix it before yunnanwang get angry :100:

**Comment by liuqipeng417** [comment]
get it ,thanks~



liuqipeng417@outlook.com
 
From: Frank
Date: 2016-01-02 02:52
To: liuqipeng417/liuqipeng417.github.io
Subject: [liuqipeng417.github.io] friend link of caoyudong is wrong (#1)
i see this: http//caoyudongcom/ , which should be http://caoyudongcom/
please fix it before yunnanwang get angry
